### ISSUE TITLE
RPI 3 and Geth

### ISSUE THREAD

**Issue by eloudsa** [EthEmbedded/Raspi-Eth-Install#4]
Hi
As I have a RPI3, I have used the procedure you described: http://ethembedded.com/?page_id=102
This procedure provides an image with Ubuntu Mate for RPI 2/3 and Geth 1.4.10.
The version of Geth is very old.

Which command(s) should be launched to ensure that Geth is up-to-date?

Thanks

S.

**Comment by phonikg** [comment]
Hello @eloudsa 

***Please see my next reply for instructions to update you geth version***

We have not been keeping up to date with our images as of late, as you can tell.  We are currently in a transition period where our focus is switching from providing images to the ethereum community at large to developing out ethereum use cases that rely on or integrate with embedded devices.  Having said this, I am always available to assist when required.

Alot of the reasons for EthEmbedded’s original purpose to exist have dissolved:

 geth dev team produces multiple ARM based binaries for download:
 ARMv5
 ARMv6
 ARMv7
 ARM64
 Light Client now included in 1.5.x - run with  `geth --light`
 C++ client not practical(used to take >6 hours to compile)
 Other Community members offering great Parity/Geth builds/img files -
http://ethraspbian.com/
 Main reason - Refocus time & resources on Implementation/Integration of Ethereum use cases

Download recent geth binaries @ https://ethereum.github.io/go-ethereum/downloads/

**Comment by phonikg** [comment]
Updating `geth`:

***BACK UP YOUR KEYFILES - If you do not know what this means, please refer to the Ethereum Homestead Documentation here: http://www.ethdocs.org/en/latest/account-management.html***

Step 1 - Remove current version:

- `$ rm /usr/local/bin/geth`

Step 2 - Download new version for RasPi3 from https://ethereum.github.io/go-ethereum/downloads/

- `wget https://gethstore.blob.core.windows.net/builds/geth-linux-arm7-1.5.4-b70acf3c.tar.gz`

Step 3 - Untar file:

- `tar zxf geth-linux-arm7-1.5.4-b70acf3c.tar.gz`

Step 4 - Move file to directory within $PATH:

- `sudo mv geth-linux-arm7-1.5.4-b70acf3c/geth /usr/local/bin/geth`

Step 5 - Clean up:

- `cd ~/`
- `rm -r geth-linux-arm7-1.5.4-b70acf3c`

Step 6 - Test the Update:

- `geth version`

and you now have the light client option so you can run `geth` with the following,

- `geth --light`


ALL DONE!

**Comment by eloudsa** [comment]
Thanks @phonikg !

**Comment by eloudsa** [comment]
I've installed EthRaspbian. Works like a charm.

Thanks again @phonikg for your advice !

**Comment by phonikg** [comment]
Your very welcome @eloudsa !
